app = "matrix-forms"

[env]
PORT = 8080
HOMESERVER = "https://converser.eu"
DEFAULT_ROOM = "!sAYXjSoGjJfOAUHaqp:matrix.org"
CORS = "*"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
